# Generated by Django 2.2.2 on 2020-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
